server:
  port: 8184
  servlet:
    context-path: /elastic-query-web-client

auth:
  data:
    custom-audience: elastic-query-web-client

elastic-query-web-client:
  webclient:
    connect-timeout-ms: 10000
    read-timeout-ms: 10000
    write-timeout-ms: 10000
    max-in-memory-size: 10485760 # 10MB
    content-type: 'application/json'
    accept-type: 'application/json'
    base-url: 'http://elastic-query-service/elastic-query-service/documents'
    service-id: elastic-query-service
    instances:
      - id: elastic-query-service-1
        host: localhost
        port: 8183
      - id: elastic-query-service-2
        host: localhost
        port: 8185
  query-by-text:
    method: POST
    uri: "/get-document-by-text"
    accept: ${elastic-query-web-client.webclient.accept-type}

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: 'elastic-query-web-client'
            client-secret: rRKCnDn8lheUYCQTDibp6NIzzEnhJ6C4
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: openid
        provider:
          keycloak:
            issuerUri: http://localhost:9990/realms/master

security:
  logout-success-url: http://localhost:8184/elastic-query-web-client
  default-client-registration-id: keycloak
  paths-to-ignore: /api-docs

user-config:
  username: test
  password: '{bcrypt}$2a$10$S4xHhYB4GeG2dPJU4evo2Ofi/let0aJc27Zjy7PCGdS9OUCTtgn2a'
  roles: USER