server:
  port: 8184
  servlet:
    context-path: /elastic-query-web-client

auth:
  data:
    custom-audience: elastic-query-web-client

elastic-query-web-client:
  webclient:
    connect-timeout-ms: 10000
    read-timeout-ms: 10000
    write-timeout-ms: 10000
    max-in-memory-size: 10485760 # 10MB
    content-type: 'application/json'
    accept-type: 'application/json'
    base-url: 'http://elastic-query-service/elastic-query-service/documents'
  query-by-text:
    method: POST
    uri: "http://elastic-query-service/elastic-query-service/documents/get-document-by-text"
    accept: ${elastic-query-web-client.webclient.accept-type}

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: 'auth-service'
            client-secret: b6VdS4EgV3uzdUDdhnsclAtzainRwhjl
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: openid
        provider:
          keycloak:
            issuerUri: http://localhost:9990/realms/master

security:
  logout-success-url: http://localhost:8184/elastic-query-web-client
  default-client-registration-id: keycloak
  paths-to-ignore: /api-docs

user-config:
  username: test
  password: '{bcrypt}$2a$10$S4xHhYB4GeG2dPJU4evo2Ofi/let0aJc27Zjy7PCGdS9OUCTtgn2a'
  roles: USER